import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.sqldelight)
}

sqldelight {
    databases {
        create("PhotonneDatabase") {
            packageName.set("com.photonne.app.db")
        }
    }
}

val photonneVersion: String = readPhotonneVersion()
// Only a prefill for the login wizard. Nothing is baked in unless passed
// explicitly (-PApiBaseUrl=...), except the emulator's host alias for Android
// debug builds — a release must never ship a developer's address.
val apiBaseUrl: String = (findProperty("ApiBaseUrl") as? String).orEmpty()
val androidDebugApiBaseUrl: String = apiBaseUrl.ifEmpty { "http://10.0.2.2:1107" }

// Release signing, from Gradle properties or environment variables (CI
// secrets). Without them the release APK is built unsigned.
fun signingValue(name: String): String? =
    (findProperty(name) as? String ?: System.getenv(name))?.takeIf { it.isNotBlank() }
val releaseKeystore: String? = signingValue("PHOTONNE_KEYSTORE_FILE")

val generatedCommonDir = layout.buildDirectory.dir("generated/photonne/commonMain/kotlin")
val writePhotonneVersion = tasks.register("writePhotonneVersion") {
    val outDir = generatedCommonDir
    val versionValue = photonneVersion
    inputs.property("photonneVersion", versionValue)
    outputs.dir(outDir)
    doLast {
        val pkgDir = outDir.get().asFile.resolve("com/photonne/app")
        pkgDir.mkdirs()
        pkgDir.resolve("PhotonneVersion.kt").writeText(
            """
            package com.photonne.app

            /** Generated by Gradle from Directory.Build.props. */
            const val PhotonneVersion: String = "$versionValue"
            """.trimIndent() + "\n"
        )
    }
}

kotlin {
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }

    // Sin iosX64: Compose Multiplatform 1.12, lifecycle 2.11 y coil 3.6 ya no publican
    // artefactos para el simulador de Mac Intel. iosSimulatorArm64 cubre el simulador en
    // Apple Silicon y iosArm64 el dispositivo, que es lo único que usamos.
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    jvm("desktop") {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(writePhotonneVersion)
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.materialIconsExtended)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)

            implementation(libs.androidx.lifecycle.viewmodel)
            implementation(libs.androidx.lifecycle.viewmodel.compose)
            implementation(libs.androidx.lifecycle.runtime.compose)

            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)

            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.client.logging)
            implementation(libs.ktor.serialization.kotlinx.json)

            implementation(libs.koin.core)
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)

            implementation(libs.multiplatform.settings)

            implementation(libs.sqldelight.runtime)

            implementation(libs.coil.compose)
            implementation(libs.coil.network.ktor)

            implementation(libs.haze)

            implementation(libs.uuid)
        }

        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.ktor.client.mock)
            implementation(libs.multiplatform.settings.test)
        }

        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.androidx.security.crypto)
            implementation(libs.androidx.documentfile)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.koin.android)
            implementation(libs.androidx.media3.exoplayer)
            implementation(libs.androidx.media3.ui)
            implementation(libs.androidx.media3.datasource.okhttp)
            implementation(libs.androidx.work.runtime)
            implementation(libs.sqldelight.android.driver)
            // Decodes a poster frame from a content:// / file:// video so device
            // videos pending upload show a thumbnail instead of a fallback icon.
            implementation(libs.coil.video)
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
            implementation(libs.sqldelight.native.driver)
        }

        val desktopMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.kotlinx.coroutines.swing)
                implementation(libs.ktor.client.cio)
                implementation(libs.multiplatform.settings.no.arg)
                implementation(libs.sqldelight.sqlite.driver)
                implementation(libs.vlcj)
                implementation(libs.java.keyring)
            }
        }
    }
}

android {
    namespace = "com.photonne.app"
    // 37 es el mínimo que exigen haze 1.7, coil 3.6 y media3 1.11 para compilar contra ellas.
    // targetSdk 36 (Android 16) es el mínimo que Google Play exige desde el 31-08-2026 para
    // publicar apps nuevas y actualizaciones. Cambios de comportamiento que afectan a la app:
    // el edge-to-edge ya no se puede desactivar (ya lo usamos, enableEdgeToEdge), el gesto de
    // atrás predictivo va por OnBackPressedDispatcher (lo usa BackHandler) y en pantallas
    // grandes (sw >= 600 dp) el sistema ignora screenOrientation="portrait".
    compileSdk = 37

    defaultConfig {
        applicationId = "com.photonne.app"
        minSdk = 26
        targetSdk = 36
        versionCode = photonneVersion.toVersionCode()
        versionName = photonneVersion
    }

    buildFeatures { buildConfig = true }

    packaging {
        resources { excludes += "/META-INF/{AL2.0,LGPL2.1}" }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    signingConfigs {
        if (releaseKeystore != null) {
            create("release") {
                storeFile = file(releaseKeystore)
                storePassword = signingValue("PHOTONNE_KEYSTORE_PASSWORD")
                keyAlias = signingValue("PHOTONNE_KEY_ALIAS")
                keyPassword = signingValue("PHOTONNE_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        getByName("debug") {
            buildConfigField("String", "API_BASE_URL", "\"$androidDebugApiBaseUrl\"")
        }
        getByName("release") {
            buildConfigField("String", "API_BASE_URL", "\"$apiBaseUrl\"")
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            if (releaseKeystore != null) {
                signingConfig = signingConfigs.getByName("release")
            }
        }
    }
}

compose.desktop {
    application {
        mainClass = "com.photonne.app.MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Photonne"
            packageVersion = photonneVersion
            // Módulos jlink que las libs cargan por reflexión y el detector no
            // ve: java.sql (driver JDBC de SQLite), java.prefs (geometría de
            // ventana y migración), jdk.unsupported (JNA: vlcj y java-keyring),
            // java.naming (logback/JNA en algunos entornos).
            modules("java.sql", "java.prefs", "java.naming", "jdk.unsupported")
            macOS { iconFile.set(project.file("icons/photonne.icns")) }
            windows { iconFile.set(project.file("icons/photonne.ico")) }
            linux { iconFile.set(project.file("icons/photonne.png")) }
        }
        buildTypes.release.proguard {
            // Sin ProGuard: vlcj/JNA, Ktor, SQLDelight y Koin dependen de
            // reflexión y no llevamos reglas; el tamaño no compensa el riesgo.
            isEnabled.set(false)
        }
        if (apiBaseUrl.isNotEmpty()) jvmArgs += "-Dphotonne.api.baseUrl=$apiBaseUrl"
    }
}

compose.resources {
    publicResClass = true
    packageOfResClass = "com.photonne.app.resources"
    generateResClass = auto
}

fun readPhotonneVersion(): String {
    val props = rootProject.file("../Directory.Build.props")
    if (props.exists()) {
        val match = Regex("<Version>([^<]+)</Version>").find(props.readText())
        if (match != null) return match.groupValues[1].trim()
    }
    return "0.0.0"
}

/**
 * MAJOR.MINOR.PATCH → MMMmmmppp (1.153.2 → 1_153_002). Play rejects any
 * upload whose versionCode isn't higher than the last one, so the encoding
 * must keep ordering: the old `major*10_000 + minor*100 + patch` overflowed
 * once minor passed 99 (1.153.2 → 25302 > 2.0.0 → 20000). Three digits per
 * part and a 2_100 major ceiling keep it under Int.MAX_VALUE and above every
 * code the old scheme produced.
 */
fun String.toVersionCode(): Int {
    val parts = split('.', '-').take(3).mapNotNull { it.toIntOrNull() }
    val major = parts.getOrNull(0) ?: 0
    val minor = parts.getOrNull(1) ?: 0
    val patch = parts.getOrNull(2) ?: 0
    require(minor < 1_000 && patch < 1_000 && major < 2_100) {
        "Version $this doesn't fit the MMMmmmppp versionCode scheme"
    }
    return major * 1_000_000 + minor * 1_000 + patch
}
