import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

val photonneVersion: String = readPhotonneVersion()
val apiBaseUrl: String = (findProperty("ApiBaseUrl") as? String).orEmpty()

val generatedCommonDir = layout.buildDirectory.dir("generated/photonne/commonMain/kotlin")
val writePhotonneVersion = tasks.register("writePhotonneVersion") {
    val outDir = generatedCommonDir
    val versionValue = photonneVersion
    inputs.property("photonneVersion", versionValue)
    outputs.dir(outDir)
    doLast {
        val pkgDir = outDir.get().asFile.resolve("com/photonne/app")
        pkgDir.mkdirs()
        pkgDir.resolve("PhotonneVersion.kt").writeText(
            """
            package com.photonne.app

            /** Generated by Gradle from Directory.Build.props. */
            const val PhotonneVersion: String = "$versionValue"
            """.trimIndent() + "\n"
        )
    }
}

kotlin {
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    jvm("desktop") {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(writePhotonneVersion)
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.materialIconsExtended)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)

            implementation(libs.androidx.lifecycle.viewmodel)
            implementation(libs.androidx.lifecycle.runtime.compose)

            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)

            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.client.logging)
            implementation(libs.ktor.serialization.kotlinx.json)

            implementation(libs.koin.core)
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)

            implementation(libs.multiplatform.settings)

            implementation(libs.coil.compose)
            implementation(libs.coil.network.ktor)

            implementation(libs.uuid)
        }

        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.ktor.client.mock)
        }

        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.androidx.security.crypto)
            implementation(libs.androidx.documentfile)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.koin.android)
            implementation(libs.androidx.media3.exoplayer)
            implementation(libs.androidx.media3.ui)
            implementation(libs.androidx.media3.datasource.okhttp)
            implementation(libs.androidx.work.runtime)
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }

        val desktopMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.kotlinx.coroutines.swing)
                implementation(libs.ktor.client.cio)
                implementation(libs.multiplatform.settings.no.arg)
            }
        }
    }
}

android {
    namespace = "com.photonne.app"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.photonne.app"
        minSdk = 26
        targetSdk = 35
        versionCode = photonneVersion.toVersionCode()
        versionName = photonneVersion
        buildConfigField("String", "API_BASE_URL", "\"$apiBaseUrl\"")
    }

    buildFeatures { buildConfig = true }

    packaging {
        resources { excludes += "/META-INF/{AL2.0,LGPL2.1}" }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildTypes {
        getByName("release") { isMinifyEnabled = false }
    }
}

compose.desktop {
    application {
        mainClass = "com.photonne.app.MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Photonne"
            packageVersion = photonneVersion
        }
        jvmArgs += "-Dphotonne.api.baseUrl=$apiBaseUrl"
    }
}

compose.resources {
    publicResClass = true
    packageOfResClass = "com.photonne.app.resources"
    generateResClass = auto
}

fun readPhotonneVersion(): String {
    val props = rootProject.file("../Directory.Build.props")
    if (props.exists()) {
        val match = Regex("<Version>([^<]+)</Version>").find(props.readText())
        if (match != null) return match.groupValues[1].trim()
    }
    return "0.0.0"
}

fun String.toVersionCode(): Int {
    val parts = split('.', '-').take(3).mapNotNull { it.toIntOrNull() }
    val major = parts.getOrNull(0) ?: 0
    val minor = parts.getOrNull(1) ?: 0
    val patch = parts.getOrNull(2) ?: 0
    return major * 10_000 + minor * 100 + patch
}
