// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Photonne.Server.Api.Shared.Data;

#nullable disable

namespace Photonne.Server.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429140000_RenameMlEntities")]
    partial class RenameMlEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Hand-written migration: BuildTargetModel intentionally left minimal because no
            // dotnet ef tooling is used in this project. The authoritative model snapshot is
            // in ApplicationDbContextModelSnapshot.cs; the [Migration] attribute above is the
            // only thing EF Core needs from this Designer to discover the migration.
        }
    }
}
