// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Photonne.Server.Api.Shared.Data;

#nullable disable

namespace Photonne.Server.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260425120000_AddFaceRecognition")]
    partial class AddFaceRecognition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Hand-written migration: BuildTargetModel intentionally left minimal because no
            // dotnet ef tooling is available in this environment. The authoritative model
            // snapshot is in ApplicationDbContextModelSnapshot.cs. EF Core only needs the
            // [Migration] attribute above for discovery; explicit Up()/Down() operations
            // are sufficient to apply this migration via Database.Migrate().
        }
    }
}
