// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Photonne.Server.Api.Shared.Data;

#nullable disable

namespace Photonne.Server.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Npgsql:PostgresExtension:vector", ",,");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverAssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoverAssetId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AlbumAsset", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("AlbumId", "AssetId");

                    b.HasIndex("AlbumId");

                    b.HasIndex("AssetId");

                    b.ToTable("AlbumAssets");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AlbumPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManagePermissions")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanWrite")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("AlbumId", "UserId")
                        .IsUnique();

                    b.ToTable("AlbumPermissions");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Caption")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedFromFolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedFromPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("ExternalLibraryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FaceRecognitionCompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FileCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FileModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFileMissing")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ObjectDetectionCompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SceneClassificationCompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TextRecognitionCompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Checksum");

                    b.HasIndex("ExternalLibraryId");

                    b.HasIndex("FileName");

                    b.HasIndex("FolderId");

                    b.HasIndex("FullPath")
                        .IsUnique();

                    b.HasIndex("IsFileMissing");

                    b.HasIndex("OwnerId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetExif", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Aperture")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("CameraMake")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CameraModel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DateTimeOriginal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("FocalLength")
                        .HasColumnType("double precision");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<int?>("Iso")
                        .HasColumnType("integer");

                    b.Property<string>("Keywords")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("Orientation")
                        .HasColumnType("integer");

                    b.Property<double?>("ShutterSpeed")
                        .HasColumnType("double precision");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.ToTable("AssetExifs");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetMlJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("JobType")
                        .HasColumnType("integer");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetId", "JobType", "Status");

                    b.ToTable("AssetMlJobs");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TagType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetId", "TagType")
                        .IsUnique();

                    b.ToTable("AssetTags");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetThumbnail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DominantColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetId", "Size")
                        .IsUnique();

                    b.ToTable("AssetThumbnails");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetUserTag", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserTagId")
                        .HasColumnType("uuid");

                    b.HasKey("AssetId", "UserTagId");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserTagId");

                    b.ToTable("AssetUserTags");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.ExternalLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CronSchedule")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("ImportSubfolders")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastScanAssetsAdded")
                        .HasColumnType("integer");

                    b.Property<int?>("LastScanAssetsFound")
                        .HasColumnType("integer");

                    b.Property<int?>("LastScanAssetsRemoved")
                        .HasColumnType("integer");

                    b.Property<int>("LastScanStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("ExternalLibraries");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.ExternalLibraryPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ExternalLibraryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("ExternalLibraryId", "UserId")
                        .IsUnique();

                    b.ToTable("ExternalLibraryPermissions");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Face", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<float>("BoundingBoxH")
                        .HasColumnType("real");

                    b.Property<float>("BoundingBoxW")
                        .HasColumnType("real");

                    b.Property<float>("BoundingBoxX")
                        .HasColumnType("real");

                    b.Property<float>("BoundingBoxY")
                        .HasColumnType("real");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Pgvector.Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(512)");

                    b.Property<bool>("IsManuallyAssigned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<float?>("SuggestedDistance")
                        .HasColumnType("real");

                    b.Property<Guid?>("SuggestedPersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SuggestedPersonId");

                    b.HasIndex("PersonId", "IsRejected");

                    b.ToTable("Faces");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ExternalLibraryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalLibraryId");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.FolderPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManagePermissions")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanWrite")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("UserId", "FolderId")
                        .IsUnique();

                    b.ToTable("FolderPermissions");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetDetectedObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<float>("BoundingBoxH")
                        .HasColumnType("real");

                    b.Property<float>("BoundingBoxW")
                        .HasColumnType("real");

                    b.Property<float>("BoundingBoxX")
                        .HasColumnType("real");

                    b.Property<float>("BoundingBoxY")
                        .HasColumnType("real");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("Label");

                    b.HasIndex("AssetId", "Label");

                    b.ToTable("AssetDetectedObjects");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetClassifiedScene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("Label");

                    b.HasIndex("AssetId", "Label");

                    b.ToTable("AssetClassifiedScenes");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetRecognizedTextLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<float>("BBoxHeight")
                        .HasColumnType("real");

                    b.Property<float>("BBoxWidth")
                        .HasColumnType("real");

                    b.Property<float>("BBoxX")
                        .HasColumnType("real");

                    b.Property<float>("BBoxY")
                        .HasColumnType("real");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LineIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetId", "LineIndex");

                    b.ToTable("AssetRecognizedTextLines");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverFaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FaceCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoverFaceId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "IsHidden");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "DeviceId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Setting", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OwnerId", "Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.SharedLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowDownload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("MaxViews")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("AssetId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("SharedLinks");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimaryAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("User");

                    b.Property<long?>("StorageQuotaBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.UserTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("UserTags");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Album", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Asset", "CoverAsset")
                        .WithMany()
                        .HasForeignKey("CoverAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "Owner")
                        .WithMany("OwnedAlbums")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoverAsset");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AlbumAsset", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Album", "Album")
                        .WithMany("AlbumAssets")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photonne.Server.Api.Shared.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AlbumPermission", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Album", "Album")
                        .WithMany("Permissions")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "User")
                        .WithMany("AlbumPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("GrantedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Asset", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.ExternalLibrary", "ExternalLibrary")
                        .WithMany("Assets")
                        .HasForeignKey("ExternalLibraryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Photonne.Server.Api.Shared.Models.Folder", "Folder")
                        .WithMany("Assets")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "Owner")
                        .WithMany("Assets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExternalLibrary");

                    b.Navigation("Folder");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetExif", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Asset", "Asset")
                        .WithOne("Exif")
                        .HasForeignKey("Photonne.Server.Api.Shared.Models.AssetExif", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetMlJob", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Asset", "Asset")
                        .WithMany("MlJobs")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetTag", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Asset", "Asset")
                        .WithMany("Tags")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetThumbnail", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Asset", "Asset")
                        .WithMany("Thumbnails")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetUserTag", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Asset", "Asset")
                        .WithMany("UserTags")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photonne.Server.Api.Shared.Models.UserTag", "UserTag")
                        .WithMany("AssetLinks")
                        .HasForeignKey("UserTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("UserTag");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.ExternalLibrary", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "Owner")
                        .WithMany("ExternalLibraries")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Face", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Asset", "Asset")
                        .WithMany("Faces")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photonne.Server.Api.Shared.Models.Person", "Person")
                        .WithMany("Faces")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Photonne.Server.Api.Shared.Models.Person", "SuggestedPerson")
                        .WithMany()
                        .HasForeignKey("SuggestedPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("Person");

                    b.Navigation("SuggestedPerson");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.ExternalLibraryPermission", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.ExternalLibrary", "ExternalLibrary")
                        .WithMany("Permissions")
                        .HasForeignKey("ExternalLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "User")
                        .WithMany("ExternalLibraryPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalLibrary");

                    b.Navigation("GrantedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Folder", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.ExternalLibrary", "ExternalLibrary")
                        .WithMany()
                        .HasForeignKey("ExternalLibraryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Photonne.Server.Api.Shared.Models.Folder", "ParentFolder")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExternalLibrary");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.FolderPermission", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Folder", "Folder")
                        .WithMany("Permissions")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "User")
                        .WithMany("FolderPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("GrantedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Notification", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetDetectedObject", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Asset", "Asset")
                        .WithMany("DetectedObjects")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Person", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Face", "CoverFace")
                        .WithMany()
                        .HasForeignKey("CoverFaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverFace");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetClassifiedScene", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Asset", "Asset")
                        .WithMany("ClassifiedScenes")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.AssetRecognizedTextLine", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Asset", "Asset")
                        .WithMany("RecognizedTextLines")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.RefreshToken", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.SharedLink", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Photonne.Server.Api.Shared.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Asset");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.UserTag", b =>
                {
                    b.HasOne("Photonne.Server.Api.Shared.Models.User", "Owner")
                        .WithMany("Tags")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Album", b =>
                {
                    b.Navigation("AlbumAssets");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Asset", b =>
                {
                    b.Navigation("Exif");

                    b.Navigation("RecognizedTextLines");

                    b.Navigation("Faces");

                    b.Navigation("MlJobs");

                    b.Navigation("DetectedObjects");

                    b.Navigation("ClassifiedScenes");

                    b.Navigation("Tags");

                    b.Navigation("Thumbnails");

                    b.Navigation("UserTags");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Person", b =>
                {
                    b.Navigation("Faces");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.ExternalLibrary", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.Folder", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Permissions");

                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.User", b =>
                {
                    b.Navigation("AlbumPermissions");

                    b.Navigation("Assets");

                    b.Navigation("ExternalLibraries");

                    b.Navigation("ExternalLibraryPermissions");

                    b.Navigation("FolderPermissions");

                    b.Navigation("OwnedAlbums");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Photonne.Server.Api.Shared.Models.UserTag", b =>
                {
                    b.Navigation("AssetLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
